### ISSUE TITLE
Gestion del Menu con una Base de Datos

### ISSUE THREAD

**Issue by LorenaIgartua** [LorenaIgartua/TPE-WEB-II#1]
Crear la funcionalidad para administrar el menu desde una Base de Datos. 
- ABM de platos
- Control de usuarios habilitados

**Comment by mujicamartin** [comment]
Login  - completo
cerre el branch Login y creo un nuevo branch VistaMenu

**Comment by mujicamartin** [comment]
Se completo todas las tareas.
