### ISSUE TITLE
MVC

### ISSUE THREAD

**Issue by LorenaIgartua** [LorenaIgartua/TPE-WEB-II#2]
Adaptar la web original aplicando MVC.
- Pretty URL
- View con Smarty (templates)
- Mantenimiento del parcial render

**Comment by LorenaIgartua** [comment]
- cree las clases para MVC, 
- adapte el router para que reconozca el Controller, 
- trabaje en el archivo risotto.js, para mantener el parcial render de la web.

**Comment by mujicamartin** [comment]
Todo Ok.
Me anduvo todo perfecto

**Comment by LorenaIgartua** [comment]
ok .... issue cerrado
